#
# Module manifest for module 'MSGraphStuff'
#
# Generated by: @AndrewZtrhgf
#
# Generated on: 7/23/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'MSGraphStuff.psm1'

# Version number of this module.
ModuleVersion = '1.1.10'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '712b70b5-7e0d-4d83-a2e5-68389e890337'

# Author of this module
Author = '@AndrewZtrhgf'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2022 @AndrewZtrhgf. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph API related functions. Some of them are explained at https://doitpshway.com.

Some of the functions:
- Expand-MgAdditionalProperties - Function for expanding "AdditionalProperties" hash property to the main object aka flattens the returned object
- Get-CodeGraphModuleDependency - Function for getting Graph SDK modules required to run given code
- Get-CodeGraphPermissionRequirement - Function for getting Graph API permissions (scopes) that are needed tu run selected code
- Invoke-GraphAPIRequest - Function for creating request against Microsoft Graph API. Unlike official one supports paging and throttling
- Invoke-GraphBatchRequest - Function for invoking Graph Api batch request(s) that handles pagination, throttling and server-side errors
- New-GraphAPIAuthHeader - Function for generating header that can be used for authentication of Graph API requests
- New-GraphBatchRequest - Function for creating PSObject that can be used in Graph Api batching requests
- ...
'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('Az.Accounts', 
               'MSAL.PS', 
               'DependencySearch')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Expand-MgAdditionalProperties', 'Get-CodeGraphModuleDependency', 
               'Get-CodeGraphPermissionRequirement', 'Get-MgGraphAllPages', 
               'Invoke-GraphAPIRequest', 'Invoke-GraphBatchRequest', 
               'New-GraphAPIAuthHeader', 'New-GraphBatchRequest'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Get-CodeGraphPermission', 'Get-CodeGraphScope', 
               'Get-GraphAPICodeModuleDependency', 'Get-GraphAPICodePermission', 
               'Get-GraphAPICodeScope', 'Get-IntuneAuthHeader', 'Invoke-MgRequest', 
               'New-IntuneAuthHeader', 'New-MgAuthHeader'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'PowerShell','Graph','Microsoft','API','MSGraph','MSGraphStuff','Batch'

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/ztrhgf/useful_powershell_modules'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '
            1.1.10
                FIXED
                    New-GraphBatchRequest - various fixes
                    Invoke-GraphBatchRequest - various fixes
            1.1.9
                FIXED
                    Invoke-GraphBatchRequest - stop returning of empty objects on failed requests
                CHANGED
                    Invoke-GraphBatchRequest - better error message
            1.1.8
                FIXED
                    New-GraphBatchRequest - "Parameter set cannot be resolved using the specified named parameters"
            1.1.7
                FIXED
                    Invoke-GraphBatchRequest - fixed "You cannot call a method on a null-valued expression" when no result is returned
                CHANGED
                    New-GraphBatchRequest - added support for using placeholder value as an request Id
            1.1.6
                FIXED
                    Invoke-GraphBatchRequest - primitive types were not returned when "dontBeautifyResult" parameter was NOT used
            1.1.5
                CHANGED
                    Invoke-GraphBatchRequest - exclude @odata.context, @odata.nextLink properties when result is in value property
                    New-GraphBatchRequest - merged url and urlWithPlaceholder parameters
                                          - added support for specifying ID for urls with placeholder
            1.1.4
                FIXED
                    Invoke-GraphBatchRequest - example typo
                                             - incorrect detection of empty body when processing results
            1.1.3
                CHANGED
                    Invoke-GraphBatchRequest - added parameter "dontAddRequestId"
                FIXED
                    Invoke-GraphBatchRequest - pipeline fixes
                    New-GraphBatchRequest - header no longer [string], other minor edits
            1.1.2
                ADDED
                    New-GraphBatchRequest
                    Invoke-GraphBatchRequest
            1.1.1
                CHANGED
                    New-GraphAPIAuthHeader - support for Az 5.x (SecureString returned by Get-AzAccessToken)

            1.1.0
                CHANGED
                    Get-CodeGraphPermissionRequirement - requires module Microsoft.Graph.Authentication (at least version 2.18.0) where output of the Find-MgGraphCommand command used for getting the permissions was significantly changed
                                                       - change in permission filtering logic, change in the returned output (error messages), ...
            1.0.11
                FIXED
                    Get-CodeGraphPermissionRequirement - ignore #requires module statements
            1.0.10
                CHANGED
                    Get-CodeGraphModuleDependency - omit type property as it is useless
            1.0.9
                ADDED
                    Get-MgGraphAllPages
                CHANGED
                    Get-CodeGraphPermissionRequirement - added Get-MgContext as command that doesnt require any privileges
                    Invoke-GraphAPIRequest - better detection of value property
            1.0.8
                FIXED
                    Get-CodeGraphModuleDependency - ignore Import-Module results, fixed DependencyPath extraction
                CHANGED
                    Get-CodeGraphPermissionRequirement - added switch allOccurrences, removed unknownDependencyAsObject parameter when searching for dependencies, because there is no real reason to return such results
            1.0.7
                CHANGED
                    Get-CodeGraphPermissionRequirement - permissions output optimized by default, to change that use dontFilterPermissions
            1.0.6
                CHANGED
                    Get-CodeGraphPermissionRequirement - new examples and checks
                ADDED
                    Get-CodeGraphModuleDependency
            1.0.5
                CHANGED
                    Get-CodeGraphPermissionRequirement - new aliases, support for both permType, added method, apiVersion to the output, added searching for graph api calls using Invoke-MsGraphRequest, Invoke-RestMethod, Invoke-WebRequest and their aliases
                FIXED
                    Get-CodeDependency - fixed skipping of modules when processJustMSGraphSDK switch is used
                '

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

