#
# Module manifest for module 'AzurePIMStuff'
#
# Generated by: @AndrewZtrhgf
#
# Generated on: 12/11/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'AzurePIMStuff.psm1'

# Version number of this module.
ModuleVersion = '0.0.3'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '38677584-d79f-4f27-81db-c6bdd8fa3b32'

# Author of this module
Author = '@AndrewZtrhgf'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2025 @AndrewZtrhgf. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell module for Azure Privileged Identity Management (PIM) automation. Some of them are explained at https://doitpshway.com.

Some of the interesting functions:
- Get-PIMGroup: Returns Azure groups with some PIM eligible assignments.
- Get-PIMGroupEligibleAssignment: Returns eligible assignments for Azure AD groups.
- Get-PIMAccountEligibleMemberOf: Returns groups where selected account(s) is eligible (via PIM) as a member.
- Get-PIMDirectoryRoleAssignmentSetting: Gets PIM assignment settings for a given Azure AD directory role.
- Get-PIMDirectoryRoleEligibleAssignment: Returns Azure Directory role eligible assignments.
- Get-PIMManagementGroupEligibleAssignment: Returns all PIM eligible IAM assignments on selected (all) Azure Management group(s).
- Get-PIMResourceRoleAssignmentSetting: Gets PIM assignment settings for a given Azure resource role at a specific scope.
- Get-PIMSubscriptionEligibleAssignment: Returns eligible role assignments on selected subscription(s) and below (resources included).
- Invoke-PIMDirectoryRoleActivation: Activates PIM eligible directory role for current user (supports FIDO2 auth context).
- Invoke-PIMResourceRoleActivation: Activates PIM eligible resource role for current user (supports FIDO2 auth context).
- New-PIMResourceEligibleRoleAssignment - function for creating PIM eligible role assignment for specified Azure resource
- Set-PIMResourceRoleAssignmentSetting - function for setting PIM assignment settings for a given Azure resource role at a specific scope

'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('Az.Accounts', 
               'Microsoft.Graph.Authentication', 
               'MSGraphStuff', 
               @{ModuleName = 'AzureCommonStuff'; ModuleVersion = '1.0.7'; })

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-PIMAccountEligibleMemberOf', 
               'Get-PIMDirectoryRoleAssignmentSetting', 
               'Get-PIMDirectoryRoleEligibleAssignment', 
               'Get-PIMGraphTokenWithClaim', 'Get-PIMGroup', 
               'Get-PIMGroupEligibleAssignment', 
               'Get-PIMManagementGroupEligibleAssignment', 
               'Get-PIMMyActiveDirectoryRole', 'Get-PIMMyActiveResourceRole', 
               'Get-PIMMyEligibleDirectoryRole', 'Get-PIMMyEligibleResourceRole', 
               'Get-PIMResourceRoleAssignmentSetting', 
               'Get-PIMSubscriptionEligibleAssignment', 'Get-PIMSupportedGroup', 
               'Invoke-PIMDirectoryRoleActivation', 
               'Invoke-PIMResourceRoleActivation', 
               'New-PIMResourceEligibleRoleAssignment', 
               'Set-PIMResourceRoleAssignmentSetting'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Activate-PIMDirectoryRole', 'Activate-PIMResourceRole', 
               'Get-AzureAccountEligibleMemberOf', 'ipdr', 'iprr'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Azure','PIM','AzurePIMStuff'

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/ztrhgf/useful_powershell_modules'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '
            0.0.3
                ADDED
                    Get-PIMGraphTokenWithClaim - function for getting Graph token with custom claims (for FIDO2 auth context scenarios)
                    Get-PIMMyActiveDirectoryRole
                    Get-PIMMyActiveResourceRole
                    Get-PIMMyEligibleResourceRole
                    Get-PIMSupportedGroup
                    Invoke-PIMDirectoryRoleActivation - function for activating PIM eligible directory role for current user (supports FIDO2 auth context)
                    Invoke-PIMResourceRoleActivation - function for activating PIM eligible resource role for current user (supports FIDO2 auth context)
                    New-PIMResourceEligibleRoleAssignment - function for creating PIM eligible role assignment for specified Azure resource
                    Set-PIMResourceRoleAssignmentSetting - function for setting PIM assignment settings for a given Azure resource role at a specific scope
                CHANGED
                    Various fixes
            0.0.2
                Added additional PIM functions for enhanced management.
            0.0.1
                Initial release with core PIM automation functions.
            '

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

