#
# Module manifest for module 'M365DefenderStuff'
#
# Generated by: @AndrewZtrhgf
#
# Generated on: 31.05.2024
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'M365DefenderStuff.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'e41efadc-6c92-41b6-92e7-1cb748be1007'

# Author of this module
Author = '@AndrewZtrhgf'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2022 @AndrewZtrhgf. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Various functions related to Microsoft Defender services (APIs). Some of them are explained at https://doitpshway.com.

    Some of the interesting functions:
    - Get-M365DefenderMachine - get specific/all machine(s)
    - Get-M365DefenderMachineUser - get machine owner
    - Get-M365DefenderMachineVulnerability - get vulnerabilities detected on the machine
    - Get-M365DefenderRecommendation - get specific/all recommendation(s) 
    - Get-M365DefenderSoftware - get specific/all software
    - Get-M365DefenderVulnerability - get specific/all vulnerability/ies
    - Get-M365DefenderVulnerabilityReport - returns customized output of Get-M365DefenderMachineVulnerability
    - Invoke-M365DefenderAdvancedQuery - returns result of the specified KQL
    - Invoke-M365DefenderSoftwareEvidenceQuery - returns Software Evidence query results from DeviceTvmSoftwareEvidenceBeta table
    - New-M365DefenderAuthHeader - creates authentication header for accessing Microsoft 365 Defender API. Supports authentication using Managed identity, current user, app secret
    - ...
    '

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('CommonStuff')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-M365DefenderMachine', 'Get-M365DefenderMachineUser', 
               'Get-M365DefenderMachineVulnerability', 
               'Get-M365DefenderRecommendation', 'Get-M365DefenderSoftware', 
               'Get-M365DefenderVulnerability', 
               'Get-M365DefenderVulnerabilityReport', 
               'Invoke-M365DefenderAdvancedQuery', 
               'Invoke-M365DefenderSoftwareEvidenceQuery', 
               'New-M365DefenderAuthHeader'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'PowerShell','M365DefenderStuff','Defender'

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/ztrhgf/useful_powershell_modules'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '
            1.0.0
                ADDED
                    Get-M365DefenderMachine
                    Get-M365DefenderMachineUser
                    Get-M365DefenderMachineVulnerability
                    Get-M365DefenderRecommendation
                    Get-M365DefenderSoftware
                    Get-M365DefenderVulnerability
                    Get-M365DefenderVulnerabilityReport
                    Invoke-M365DefenderAdvancedQuery
                    Invoke-M365DefenderSoftwareEvidenceQuery
                    New-M365DefenderAuthHeader
            '

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

